# STUN/TURN lab
#
# ISEP, 2026
# 

LAB_DESCRIPTION=STUN/TURN lab
LAB_VERSION=20260219

host_a1[0]=netA
host_a1[image]='miguelleitao/stun-isep'
host_a2[0]=netA
host_a2[image]='miguelleitao/stun-isep'
host_a3[0]=netA
host_a3[image]='miguelleitao/stun-isep'

host_b1[0]=netB
host_b1[image]='miguelleitao/stun-isep'
host_b2[0]=netB
host_b2[image]='miguelleitao/stun-isep'
host_b3[0]=netB
host_b3[image]='miguelleitao/stun-isep'

ra[0]=netA
ra[1]=internet
rb[0]=netB
rb[1]=internet

host_i[0]=internet

stun[0]=internet
stun[bridged]=true
stun[image]='miguelleitao/stun-isep'





