# /etc/turnserver.conf

# Endereço do servidor na rede pública
listening-ip=203.0.113.99
listening-port=3478

# Identidade do serviço
realm=lab.turn
fingerprint
lt-cred-mech
no-multicast-peers
no-cli

# Utilizador TURN
user=isep:isep123

# Transportes aceites
protocols=udp,tcp

# Log
log-file=/var/log/turnserver.log
simple-log
